"""Compile the audited Modex membership snapshot into immutable grouping rules.

No display-name fuzzy matching, FormIDs, plugin aliases, or transitive unions.
Items explicitly not equipped are not positive outfit-membership evidence.
The base-game plugins remain outside the generator's supported scan scope.
"""
import argparse
import collections
import hashlib
import json
import pathlib

BASE = {'skyrim.esm', 'update.esm', 'dawnguard.esm', 'hearthfires.esm', 'dragonborn.esm'}


def compile_rules(corpus):
    rules = []
    for reference in corpus['references']:
        by_plugin = collections.defaultdict(set)
        for item in reference['items']:
            if item['equipped'] and item['plugin'].lower() not in BASE:
                by_plugin[item['plugin'].lower()].add(item['editorID'].lower())
        for plugin, members in sorted(by_plugin.items()):
            if len(members) >= 2:
                rules.append((reference['name'], plugin, sorted(members)))
    frequency = collections.Counter((plugin, member) for _, plugin, members in rules for member in members)
    lines = ['// Generated by scripts/generate-community-grouping.py; do not edit.',
             '// Source snapshot SHA256: ' + hashlib.sha256(json.dumps(corpus['sourceHashes'], sort_keys=True).encode()).hexdigest(),
             'constexpr CommunityMember kCommunityMembers[]{']
    for _, plugin, members in rules:
        minimum = min(frequency[plugin, member] for member in members)
        for member in members:
            anchor = frequency[plugin, member] == minimum
            lines.append('  {' + json.dumps(member, ensure_ascii=False) + ', ' + str(anchor).lower() + '},')
    lines += ['};', 'constexpr CommunityReference kCommunityReferences[]{']
    offset = 0
    for name, plugin, members in rules:
        lines.append('  {' + ', '.join([json.dumps(name, ensure_ascii=False), json.dumps(plugin), str(offset), str(len(members))]) + '},')
        offset += len(members)
    lines += ['};', '']
    return '\n'.join(lines), rules


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('corpus', type=pathlib.Path)
    parser.add_argument('output', type=pathlib.Path)
    args = parser.parse_args()
    content, rules = compile_rules(json.loads(args.corpus.read_text(encoding='utf-8')))
    args.output.write_text(content, encoding='utf-8')
    print(f'{len(rules)} plugin-scoped reference groups, {sum(len(r[2]) for r in rules)} equipped membership entries')


if __name__ == '__main__':
    main()
